name = "willena-proxy-test"
main = "index.js"
compatibility_date = "2025-12-07"

# Deploy to workers.dev for testing
workers_dev = true

# Uncomment and set your account_id if you want to bind routes from wrangler
# account_id = "your-cloudflare-account-id"
