name = "progress-summary"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV namespace for leaderboard cache
[[kv_namespaces]]
binding = "LEADERBOARD_CACHE"
id = "b1c31b6ddc044390a1aa9158d635e70f"

[dev]
port = 8790
local_protocol = "http"
